# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d203d3bf9ea3f139ceee4d7dff89b960865c8d2a40d869dc6453d989fd59e5bf9463f6a7a6fbfb3562e66c6920ea62b310285432f4ba5c9c00a9725e8a4881

test:
  secret_key_base: 9bcb5f537ac8f869448e9e34f217b1240aa6f122bca7e99cdd456b9e0e3ab6459667eaa08a1cef91fa0e5fd5e687179242aad18adc64b009cff407801b670117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
